name: Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.5.0

    - name: Set up JDK
      uses: actions/setup-java@v2.6.3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file ../../pom.xml
      with:
        maven-version: '3.8.4'

